GitHub Actions CI
UM-2021/speech-to-text-app pull request #12
Opened 2021-05-01 14:32 UTC by JFer11

Continuous Integration with Github Actions added.

2021-05-01 15:33 UTC, jopealgorta24 requested changes

2021-05-01 15:33 UTC, jopealgorta24 commented on .github/workflows/continuous_integration.yml
> +on: [pull_request]
@JFer11 encontre la manera para triggerear los tests solo si se hacen cambios en una folder:
```
on:
  pull_request:
    paths:
      - 'server/**'
```

2021-05-02 16:01 UTC, JFer11 commented on .github/workflows/continuous_integration.yml
> +on: [pull_request]
Full picadooo, que rica, lo agrego ;)

2021-05-03 19:17 UTC, jopealgorta24 requested changes

2021-05-03 19:17 UTC, jopealgorta24 commented on .github/workflows/continuous_integration.yml
> +    paths:
Perdon por atomizar fer, pudiste probar que funciona? Tendrias que haber creado unos pr de prueba. Haria dos tests,

- Cuando afecta la carpeta server se ejecutan
- Cuando no, no se ejecutan.

2021-05-07 14:01 UTC, JFer11 commented on .github/workflows/continuous_integration.yml
> +    paths:
Si, estaba esperando un aprove, porque no lo podia mergear. Esta listo.

2021-05-07 14:13 UTC, ghost approved these changes

2021-05-07 14:14 UTC, merged