Filtrado de sucursales, corrección de ruteo, recompilado y envio de respuestas al final de auditoria
UM-2021/speech-to-text-app pull request #20
Opened 2021-05-24 19:01 UTC by jstaricco10

- Filtrado de sucursales
- Correcciones a nivel de ruteo
- Recopilado de respuestas
- Envío de respuestas

2021-05-24 19:59 UTC, jalgorta-verimatrix commented on client/src/components/Pregunta.tsx
> +  // };
Tenesmos que hacer esto cuanto antes, definir bien que queda y queno, pero no puede haber mas codigo comentado

2021-05-24 20:01 UTC, jalgorta-verimatrix commented on client/src/helpers/PrivateRoute.tsx
> +          </>
Porque se cambio esto?

2021-05-24 20:03 UTC, jalgorta-verimatrix commented on client/src/pages/RespuestasAuditoria.tsx
> +    <>
SI es una page Deberia tener el layour general de una page  IonPage > IonHeader > IonContent. Si no tiene que ser un component pa mi.

2021-05-24 20:04 UTC, jalgorta-verimatrix commented on client/src/pages/Sucursales.tsx
> +  );
Estos estilos me matan jajaj es re cortita la linea y ya me la quiebra en 4

2021-05-24 20:07 UTC, jalgorta-verimatrix commented on client/src/pages/Sucursales.tsx
> +              if (s.nombre.toLowerCase().includes(searchText)) {
searchText tendria que hacerse un tolowercase tambien no?

2021-05-24 20:07 UTC, jalgorta-verimatrix requested changes
Perfecto Juanma, unos detalles nomas

2021-05-26 21:03 UTC, jopealgorta24 commented on client/src/pages/Sucursales.tsx
> +              ) {
me mata que me separe en mil lineas el codigooooo jaja

2021-05-26 21:03 UTC, jopealgorta24 approved these changes

2021-05-26 21:03 UTC, merged