errores
UM-2021/speech-to-text-app pull request #23
Opened 2021-05-29 19:12 UTC by IgnacioCogliatti

2021-05-29 19:59 UTC, GermanAbuArab commented on server/sucursal/views.py
> +    def create(self, request):
Crego que django cuando le mandas cambos no-null vacios, te responde con un 400

2021-05-29 20:03 UTC, GermanAbuArab requested changes

2021-05-29 20:03 UTC, GermanAbuArab commented on server/auditoria/views.py
> +    def create(self, request):
Lo mismo, no creo que sea necesario sobrescribir el create para validar los campos nullos

2021-05-30 14:32 UTC, jopealgorta24 requested changes

2021-05-30 14:32 UTC, ghost commented on server/sucursal/views.py
> +        return Response(datosSerializados.errors, status=status.HTTP_400_BAD_REQUEST)
Estas son las cosas que no estamos para nada alineados. @IgnacioCogliatti esta bien la logica, pero esas validaciones ya las hace django. Los campos required ya los valida el serializer pq se fija si los campos son tienen `null=True` o `blank=True`.  Perdon pero lo voy a cerrar sin mergear este. La idea era que tnegas en cuenta casos borde, casos de dependencias y ese tipo de acciones que no son genericas en una API Rest.

2021-06-06 19:54 UTC, closed without merging