Se pueden subir audios a s3 cambiando el .env.dev
UM-2021/speech-to-text-app pull request #34
Opened 2021-06-06 21:51 UTC by GermanAbuArab

Pidanle las credenciales a mateo

2021-06-06 21:53 UTC, lborrazas approved these changes, later dismissed
Bien borrado, todo lo que ya no va de prueba, y la configuración con el "public" bucket, luego tenemos que ver si hacemos una separación con el private bucket o no, en otro pr :)

2021-06-09 20:58 UTC, IgnacioCogliatti approved these changes, later dismissed

2021-06-09 21:05 UTC, JFer11 requested changes

2021-06-09 21:05 UTC, JFer11 commented on server/api/models.py
> +        audio = models.FileField(upload_to='audios_de_respuesta/', null=True, blank=True)
Tengo entendido que no esta bueno tener lógica dentro de un modelo. Lo que se hace generalmente si queres guardar un archivo dependiendo de ciertas condiciones, es pasarle al FileField una función, en vez de un path.

Por poner un ejemplo:
```
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class MyModel(models.Model):
    upload = models.FileField(upload_to=user_directory_path)
```
Te recomiendo que le pegues una leidita a la sección File Field para entenderlo bien, literal son solo 2 minutos:
https://docs.djangoproject.com/en/3.2/ref/models/fields/#filefield

Ahora, por otro lado veo que además utilizas un parámetro llamado storage, la verdad nunca lo había utilizado, pero no me suena que sea el mejor camino.
A priori, para guardar los datos, hubiera pensado crear una función como te mostré anteriormente, y hacer la lógica que hiciste ahi dentro. Además, por lo que estuve mirando, no se si es una buena práctica pasarle el storage como argumento. Me parece que eventualmente nos va a dar mas dolores de cabeza. Capaz me equivoco, pero en algun post de stack overflow leí eso. Por ejemplo aca: https://stackoverflow.com/questions/59437637/django-use-private-s3-storage-only-in-production-environment

Capaz podemos juntarnos y ver que hace bien ese parámetro para ver como sacarlo de ahí.
@JopeAlgorta @jopealgorta24 Vos alguna vez utilizaste el "storage"?

2021-06-11 04:44 UTC, lborrazas approved these changes

2021-06-11 04:45 UTC, JFer11 approved these changes

2021-06-11 04:45 UTC, merged