[IDSII-6] Audio conversion to text
UM-2021/speech-to-text-app pull request #4
Opened 2021-04-22 03:45 UTC by saguirregaray

Summary: 
This PR has the necessary changes to ingest audio data (in a binary format) and convert it to text using IBM Speech to text.

Changes:
- IBM Speech to Text service authentication.
- Audio conversion functions and tests. 
- Model changes to support audio files.

2021-04-23 13:52 UTC, jopealgorta24 commented on server/Pipfile
> +ibm_cloud_sdk_core = "3.9.0"
Son dev-packages? no los necesitas en produccion?

2021-04-23 13:54 UTC, saguirregaray commented on server/Pipfile
> +ibm_cloud_sdk_core = "3.9.0"
No sabia donde iban, los cambio de lugar

2021-04-23 13:57 UTC, jopealgorta24 requested changes

2021-04-23 13:57 UTC, jopealgorta24 commented on server/api/models.py
> +               self.coord_ing
Esto no lo hiciste vos serri, pero @JFer11 el campo de coordenadas es lng con L, de longitud.

2021-04-23 13:57 UTC, jopealgorta24 commented on server/audio/src/main/speech_to_text.py
> +        json.dumps(
Porque si viene en Json lo dumpeas y lo loadeas? Curiosidad nomas

2021-04-23 13:58 UTC, jopealgorta24 commented on server/Pipfile
> +ibm_cloud_sdk_core = "3.9.0"
ponelos en packages, porque sino cuando haces el build, no te los agrega.

2021-04-23 16:13 UTC, saguirregaray commented on server/api/models.py
> +               self.coord_ing
Lo cambio

2021-04-23 16:15 UTC, saguirregaray commented on server/audio/src/main/speech_to_text.py
> +        json.dumps(
No reason, tenia otra lógica y cuando la cambie me olvidé de sacar eso. Gracias!

2021-04-24 11:57 UTC, jopealgorta24 commented on server/api/models.py
> +        return self.id, self.pregunta, self.audio, self.categoria, self.esquema_id
El __str__ es para cuando se muestra en el django admin, no tiene sentido mostrar el audio no? Perdon si rompo las bolas jajaj

2021-04-24 11:58 UTC, jopealgorta24 approved these changes

2021-04-24 11:58 UTC, merged